# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true

java_version=[VERSIONED]

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=[VERSIONED]
last_minecraft_version=[VERSIONED]
loader_version=[VERSIONED]

# Mod Properties
mod_version=1.0-SNAPSHOT
maven_group=tronka
archives_base_name=DiscordJustSync

# Mod Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=[VERSIONED]
fabric_permissions_api_version=[VERSIONED]
luckperms_api_version=5.4
floodgate_api_version=2.2.4-SNAPSHOT
banhammer_version=0.12.0+1.21.2
vanish_version=[VERSIONED]
placeholder_api_version=[VERSIONED]

# Dependencies
jda_version=5.3.2
webhooks_version=0.8.4
toml4j_commit=e70ac9f
